using SQLST.Application;
using SQLST.Contracts;
using SQLST.Infrastructure;

namespace SQLST.Application.Tests;

/// <summary>v8-S1 — "Tablo oluştur" sihirbazının SAF CREATE TABLE üreticisi (MSSQL).</summary>
public class TabloOlusturucuTests
{
    private static readonly ILehce Mssql = new MssqlLehcesi(new DpapiSecretProtector());

    private static (string? Sql, string? Hata) Uret(YeniTablo t) => TabloOlusturucu.Uret(t, Mssql);

    [Fact]
    public void Temel_tablo_PK_identity_ve_default()
    {
        var t = new YeniTablo("dbo", "Musteri",
        [
            new YeniKolon("Id", "int", PkMi: true, IdentityMi: true),
            new YeniKolon("Ad", "nvarchar(100)", NullOlabilir: false),
            new YeniKolon("Aktif", "bit", Varsayilan: "1"),
        ]);

        (string? sql, string? hata) = Uret(t);

        Assert.Null(hata);
        Assert.Equal(
            "CREATE TABLE [dbo].[Musteri] (\n"
            + "    [Id] int IDENTITY(1,1) NOT NULL,\n"
            + "    [Ad] nvarchar(100) NOT NULL,\n"
            + "    [Aktif] bit NOT NULL DEFAULT (1),\n"
            + "    CONSTRAINT [PK_Musteri] PRIMARY KEY ([Id])\n"
            + ");",
            sql);
    }

    [Fact]
    public void Bilesik_PK_ve_semasiz()
    {
        var t = new YeniTablo(null, "Kalem",
        [
            new YeniKolon("SiparisId", "int", PkMi: true),
            new YeniKolon("SatirNo", "int", PkMi: true),
        ]);

        (string? sql, _) = Uret(t);

        Assert.Contains("CREATE TABLE [Kalem] (", sql!, StringComparison.Ordinal);
        Assert.Contains("PRIMARY KEY ([SiparisId], [SatirNo])", sql!, StringComparison.Ordinal);
    }

    [Theory]
    [InlineData("", "Ad", "Tablo adı")]
    [InlineData("T", "", "En az bir kolon")]
    public void Bos_ad_veya_kolonsuz_hata(string tabloAd, string kolonAd, string beklenen)
    {
        IReadOnlyList<YeniKolon> kolonlar = kolonAd.Length > 0 ? [new YeniKolon(kolonAd, "int")] : [];
        (string? sql, string? hata) = Uret(new YeniTablo("dbo", tabloAd, kolonlar));

        Assert.Null(sql);
        Assert.Contains(beklenen, hata!, StringComparison.Ordinal);
    }

    [Fact]
    public void PK_kolon_NULL_olamaz()
    {
        (_, string? hata) = Uret(new YeniTablo("dbo", "T",
            [new YeniKolon("Id", "int", NullOlabilir: true, PkMi: true)]));
        Assert.Contains("NULL olamaz", hata!, StringComparison.Ordinal);
    }

    [Fact]
    public void Tekrar_eden_kolon_adi_hata()
    {
        (_, string? hata) = Uret(new YeniTablo("dbo", "T",
            [new YeniKolon("Ad", "int"), new YeniKolon("ad", "nvarchar(10)")]));
        Assert.Contains("tekrar", hata!, StringComparison.Ordinal);
    }

    [Fact]
    public void Iki_identity_hata()
    {
        (_, string? hata) = Uret(new YeniTablo("dbo", "T",
            [new YeniKolon("A", "int", IdentityMi: true), new YeniKolon("B", "int", IdentityMi: true)]));
        Assert.Contains("otomatik artan", hata!, StringComparison.Ordinal);
    }

    // ── Motor bazlı CREATE sözdizimi (v8-S2) ──────────────────────────────────

    private static readonly ISecretProtector Koruyucu = new DpapiSecretProtector();

    [Fact]
    public void Postgres_GENERATED_identity_ve_text()
    {
        var t = new YeniTablo("dbo", "Musteri",
            [new YeniKolon("Id", "int", PkMi: true, IdentityMi: true), new YeniKolon("Ad", "text")]);

        (string? sql, _) = TabloOlusturucu.Uret(t, new PostgresLehcesi(Koruyucu));

        Assert.Equal(
            "CREATE TABLE \"dbo\".\"Musteri\" (\n"
            + "    \"Id\" int GENERATED BY DEFAULT AS IDENTITY,\n"
            + "    \"Ad\" text NOT NULL,\n"
            + "    CONSTRAINT \"PK_Musteri\" PRIMARY KEY (\"Id\")\n"
            + ");",
            sql);
    }

    [Fact]
    public void MySql_AUTO_INCREMENT_ve_semasiz()
    {
        var t = new YeniTablo("app", "Musteri",
            [new YeniKolon("Id", "int", PkMi: true, IdentityMi: true), new YeniKolon("Ad", "varchar(100)")]);

        (string? sql, _) = TabloOlusturucu.Uret(t, new MySqlLehcesi(Koruyucu));

        Assert.Equal(
            "CREATE TABLE `Musteri` (\n"
            + "    `Id` int NOT NULL AUTO_INCREMENT,\n"
            + "    `Ad` varchar(100) NOT NULL,\n"
            + "    CONSTRAINT `PK_Musteri` PRIMARY KEY (`Id`)\n"
            + ");",
            sql);
    }

    [Fact]
    public void Oracle_GENERATED_ve_ifade_sonu_yok()
    {
        var t = new YeniTablo("DBO", "MUSTERI",
            [new YeniKolon("ID", "number", PkMi: true, IdentityMi: true), new YeniKolon("AD", "varchar2(100)")]);

        (string? sql, _) = TabloOlusturucu.Uret(t, new OracleLehcesi(Koruyucu));

        Assert.Equal(
            "CREATE TABLE \"DBO\".\"MUSTERI\" (\n"
            + "    \"ID\" number GENERATED BY DEFAULT AS IDENTITY,\n"
            + "    \"AD\" varchar2(100) NOT NULL,\n"
            + "    CONSTRAINT \"PK_MUSTERI\" PRIMARY KEY (\"ID\")\n"
            + ")",  // Oracle'da ifade sonu ; yok
            sql);
    }

    [Fact]
    public void Identity_kolonda_DEFAULT_verilmez()
    {
        // Identity + default çakışır → default atlanır (MSSQL).
        var t = new YeniTablo("dbo", "T", [new YeniKolon("Id", "int", IdentityMi: true, Varsayilan: "5")]);
        (string? sql, _) = Uret(t);
        Assert.DoesNotContain("DEFAULT", sql!, StringComparison.Ordinal);
    }

    // ── Kısıtlar: UNIQUE · CHECK · FK (borç kapanışı) ─────────────────────────

    [Fact]
    public void Create_unique_check_ve_fk_kisitlari()
    {
        var t = new YeniTablo("dbo", "Musteri",
        [
            new YeniKolon("Id", "int", PkMi: true, IdentityMi: true),
            new YeniKolon("Eposta", "nvarchar(200)", BenzersizMi: true),
            new YeniKolon("Yas", "int", Kontrol: "Yas >= 0"),
            new YeniKolon("SehirId", "int", FkTablo: "dbo.Sehir", FkKolon: "Id"),
        ]);

        (string? sql, string? hata) = Uret(t);

        Assert.Null(hata);
        Assert.Contains("CONSTRAINT [UQ_Musteri_Eposta] UNIQUE ([Eposta])", sql!, StringComparison.Ordinal);
        Assert.Contains("CONSTRAINT [CK_Musteri_Yas] CHECK (Yas >= 0)", sql!, StringComparison.Ordinal);
        Assert.Contains(
            "CONSTRAINT [FK_Musteri_SehirId] FOREIGN KEY ([SehirId]) REFERENCES [dbo].[Sehir] ([Id])",
            sql!, StringComparison.Ordinal);
    }

    [Fact]
    public void Fk_hedef_tablo_kolonundan_biri_eksikse_hata()
    {
        (_, string? hata) = Uret(new YeniTablo("dbo", "T",
            [new YeniKolon("SehirId", "int", FkTablo: "Sehir")])); // FkKolon yok
        Assert.Contains("yabancı anahtar", hata!, StringComparison.Ordinal);
    }

    [Fact]
    public void Fk_semasiz_hedef_tek_parca_tirnaklanir()
    {
        (string? sql, _) = Uret(new YeniTablo("dbo", "T",
            [new YeniKolon("Fk", "int", FkTablo: "Sehir", FkKolon: "Id")]));
        Assert.Contains("REFERENCES [Sehir] ([Id])", sql!, StringComparison.Ordinal);
    }

    // ── ALTER (sütun ekleme) kipi ─────────────────────────────────────────────

    [Fact]
    public void Alter_mssql_add_kolonlar_ve_kisit_ayri_ifade()
    {
        var t = new YeniTablo("dbo", "Musteri",
        [
            new YeniKolon("Telefon", "nvarchar(20)", NullOlabilir: true),
            new YeniKolon("Eposta", "nvarchar(200)", BenzersizMi: true),
        ], TabloModu.Ekle);

        (string? sql, string? hata) = Uret(t);

        Assert.Null(hata);
        Assert.Contains("ALTER TABLE [dbo].[Musteri] ADD [Telefon] nvarchar(20) NULL, [Eposta] nvarchar(200) NOT NULL;",
            sql!, StringComparison.Ordinal);
        // UNIQUE kolon eklendikten SONRA ayrı ADD CONSTRAINT ile
        Assert.Contains("ALTER TABLE [dbo].[Musteri] ADD CONSTRAINT [UQ_Musteri_Eposta] UNIQUE ([Eposta]);",
            sql!, StringComparison.Ordinal);
    }

    [Fact]
    public void Alter_postgres_ve_mysql_ADD_COLUMN_oracle_parantez()
    {
        var kolonlar = new[] { new YeniKolon("Telefon", "varchar(20)", NullOlabilir: true) };

        (string? pg, _) = TabloOlusturucu.Uret(
            new YeniTablo("public", "musteri", kolonlar, TabloModu.Ekle), new PostgresLehcesi(Koruyucu));
        (string? my, _) = TabloOlusturucu.Uret(
            new YeniTablo(null, "musteri", kolonlar, TabloModu.Ekle), new MySqlLehcesi(Koruyucu));
        (string? or, _) = TabloOlusturucu.Uret(
            new YeniTablo("HR", "MUSTERI", kolonlar, TabloModu.Ekle), new OracleLehcesi(Koruyucu));

        Assert.Contains("ADD COLUMN \"Telefon\" varchar(20) NULL", pg!, StringComparison.Ordinal);
        Assert.Contains("ADD COLUMN `Telefon` varchar(20) NULL", my!, StringComparison.Ordinal);
        Assert.Contains("ALTER TABLE \"HR\".\"MUSTERI\" ADD (\"Telefon\" varchar(20))", or!, StringComparison.Ordinal);
        Assert.DoesNotContain(";", or!); // Oracle'da ifade sonu ; yok
    }

    [Theory]
    [InlineData(true, false, "PK")]
    [InlineData(false, true, "IDENTITY")]
    public void Alter_kipinde_PK_ve_IDENTITY_engellenir(bool pk, bool identity, string beklenen)
    {
        (_, string? hata) = Uret(new YeniTablo("dbo", "T",
            [new YeniKolon("Yeni", "int", PkMi: pk, IdentityMi: identity)], TabloModu.Ekle));
        Assert.Contains(beklenen, hata!, StringComparison.Ordinal);
    }
}
